# Generated by Django 5.2.3 on 2025-07-20 10:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enneagram', '0002_testresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnneagramType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_number', models.PositiveSmallIntegerField(choices=[(1, 'تیپ ۱: کمال\u200cگرا'), (2, 'تیپ ۲: یاری\u200cرسان'), (3, 'تیپ ۳: موفقیت\u200cطلب'), (4, 'تیپ ۴: فردگرا'), (5, 'تیپ ۵: جستجوگر'), (6, 'تیپ ۶: وفادار'), (7, 'تیپ ۷: خوش\u200cگذران'), (8, 'تیپ ۸: چالش\u200cگر'), (9, 'تیپ ۹: صلح\u200cطلب')], unique=True)),
                ('title', models.CharField(max_length=100)),
                ('short_description', models.TextField(max_length=200)),
                ('main_image', models.ImageField(upload_to='enneagram_types/')),
                ('overview', ckeditor.fields.RichTextField(verbose_name='معرفی کلی')),
                ('strengths', ckeditor.fields.RichTextField(verbose_name='نقاط قوت')),
                ('weaknesses', ckeditor.fields.RichTextField(verbose_name='نقاط ضعف')),
                ('growth_tips', ckeditor.fields.RichTextField(verbose_name='راهکارهای رشد')),
                ('relationships', ckeditor.fields.RichTextField(verbose_name='روابط')),
                ('career_paths', ckeditor.fields.RichTextField(verbose_name='مسیر شغلی')),
                ('famous_examples', models.TextField(verbose_name='افراد مشهور')),
                ('color_code', models.CharField(default='#FFD700', max_length=7, verbose_name='کد رنگ')),
            ],
            options={
                'verbose_name': 'تیپ انیاگرام',
                'verbose_name_plural': 'تیپ\u200cهای انیاگرام',
            },
        ),
    ]
