# Generated by Django 5.2.3 on 2025-07-26 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('enneagram', '0003_enneagramtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(verbose_name='English Question Text')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersianQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(verbose_name='متن سوال فارسی')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='option',
            name='question',
        ),
        migrations.AlterModelOptions(
            name='testresult',
            options={'verbose_name': 'نتیجه تست', 'verbose_name_plural': 'نتایج تست'},
        ),
        migrations.AddField(
            model_name='option',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='option',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='enneagramtype',
            name='main_image',
            field=models.ImageField(upload_to='enneagram_types/', verbose_name='تصویر اصلی'),
        ),
        migrations.AlterField(
            model_name='enneagramtype',
            name='short_description',
            field=models.TextField(max_length=200, verbose_name='توضیح کوتاه'),
        ),
        migrations.AlterField(
            model_name='enneagramtype',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='enneagramtype',
            name='type_number',
            field=models.PositiveSmallIntegerField(choices=[(1, 'تیپ ۱: کمال\u200cگرا'), (2, 'تیپ ۲: یاری\u200cرسان'), (3, 'تیپ ۳: موفقیت\u200cطلب'), (4, 'تیپ ۴: فردگرا'), (5, 'تیپ ۵: جستجوگر'), (6, 'تیپ ۶: وفادار'), (7, 'تیپ ۷: خوش\u200cگذران'), (8, 'تیپ ۸: چالش\u200cگر'), (9, 'تیپ ۹: صلح\u200cطلب')], unique=True, verbose_name='شماره تیپ'),
        ),
        migrations.AlterField(
            model_name='option',
            name='enneagram_type',
            field=models.PositiveSmallIntegerField(verbose_name='تیپ انیاگرام'),
        ),
        migrations.AlterField(
            model_name='option',
            name='text',
            field=models.CharField(max_length=255, verbose_name='متن گزینه'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='answers',
            field=models.JSONField(verbose_name='پاسخ\u200cها'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='result_type',
            field=models.IntegerField(verbose_name='تیپ نتیجه'),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
