# Generated by Django 5.2.3 on 2025-07-26 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enneagram', '0004_englishquestion_persianquestion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='option',
            name='object_id',
        ),
        migrations.AddField(
            model_name='option',
            name='english_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='enneagram.englishquestion'),
        ),
        migrations.AddField(
            model_name='option',
            name='persian_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='enneagram.persianquestion'),
        ),
    ]
