# Generated by Django 5.2.3 on 2025-07-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام نمونه')),
            ],
            options={
                'verbose_name': 'مدل نمونه',
                'verbose_name_plural': 'مدل\u200cهای نمونه',
            },
        ),
    ]
